/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAtelierRouteImport } from './routes/_authenticated/atelier'
import { Route as AuthenticatedCatalogueRouteImport } from './routes/_authenticated/catalogue'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMesuresRouteImport } from './routes/_authenticated/mesures'
import { Route as AuthenticatedRendezVousRouteImport } from './routes/_authenticated/rendez-vous'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedCommandesIndexRouteImport } from './routes/_authenticated/commandes.index'
import { Route as AuthenticatedCommandesOrderIdRouteImport } from './routes/_authenticated/commandes.$orderId'
import { Route as AuthenticatedCommandesNouvelleRouteImport } from './routes/_authenticated/commandes.nouvelle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtelierRoute = AuthenticatedAtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogueRoute = AuthenticatedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesuresRoute = AuthenticatedMesuresRouteImport.update({
  id: '/mesures',
  path: '/mesures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRendezVousRoute = AuthenticatedRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandesIndexRoute =
  AuthenticatedCommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandesOrderIdRoute =
  AuthenticatedCommandesOrderIdRouteImport.update({
    id: '/commandes/$orderId',
    path: '/commandes/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandesNouvelleRoute =
  AuthenticatedCommandesNouvelleRouteImport.update({
    id: '/commandes/nouvelle',
    path: '/commandes/nouvelle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atelier': typeof AuthenticatedAtelierRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mesures': typeof AuthenticatedMesuresRoute
  '/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/commandes/$orderId': typeof AuthenticatedCommandesOrderIdRoute
  '/commandes/nouvelle': typeof AuthenticatedCommandesNouvelleRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/commandes/': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atelier': typeof AuthenticatedAtelierRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mesures': typeof AuthenticatedMesuresRoute
  '/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/commandes/$orderId': typeof AuthenticatedCommandesOrderIdRoute
  '/commandes/nouvelle': typeof AuthenticatedCommandesNouvelleRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/commandes': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atelier': typeof AuthenticatedAtelierRoute
  '/_authenticated/catalogue': typeof AuthenticatedCatalogueRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mesures': typeof AuthenticatedMesuresRoute
  '/_authenticated/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/commandes/$orderId': typeof AuthenticatedCommandesOrderIdRoute
  '/_authenticated/commandes/nouvelle': typeof AuthenticatedCommandesNouvelleRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/commandes/': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atelier'
    | '/catalogue'
    | '/dashboard'
    | '/mesures'
    | '/rendez-vous'
    | '/statistiques'
    | '/clients/$clientId'
    | '/commandes/$orderId'
    | '/commandes/nouvelle'
    | '/clients/'
    | '/commandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/atelier'
    | '/catalogue'
    | '/dashboard'
    | '/mesures'
    | '/rendez-vous'
    | '/statistiques'
    | '/clients/$clientId'
    | '/commandes/$orderId'
    | '/commandes/nouvelle'
    | '/clients'
    | '/commandes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atelier'
    | '/_authenticated/catalogue'
    | '/_authenticated/dashboard'
    | '/_authenticated/mesures'
    | '/_authenticated/rendez-vous'
    | '/_authenticated/statistiques'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/commandes/$orderId'
    | '/_authenticated/commandes/nouvelle'
    | '/_authenticated/clients/'
    | '/_authenticated/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atelier': {
      id: '/_authenticated/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AuthenticatedAtelierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogue': {
      id: '/_authenticated/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesures': {
      id: '/_authenticated/mesures'
      path: '/mesures'
      fullPath: '/mesures'
      preLoaderRoute: typeof AuthenticatedMesuresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rendez-vous': {
      id: '/_authenticated/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof AuthenticatedRendezVousRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commandes/': {
      id: '/_authenticated/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof AuthenticatedCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commandes/$orderId': {
      id: '/_authenticated/commandes/$orderId'
      path: '/commandes/$orderId'
      fullPath: '/commandes/$orderId'
      preLoaderRoute: typeof AuthenticatedCommandesOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commandes/nouvelle': {
      id: '/_authenticated/commandes/nouvelle'
      path: '/commandes/nouvelle'
      fullPath: '/commandes/nouvelle'
      preLoaderRoute: typeof AuthenticatedCommandesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtelierRoute: typeof AuthenticatedAtelierRoute
  AuthenticatedCatalogueRoute: typeof AuthenticatedCatalogueRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMesuresRoute: typeof AuthenticatedMesuresRoute
  AuthenticatedRendezVousRoute: typeof AuthenticatedRendezVousRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedCommandesOrderIdRoute: typeof AuthenticatedCommandesOrderIdRoute
  AuthenticatedCommandesNouvelleRoute: typeof AuthenticatedCommandesNouvelleRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedCommandesIndexRoute: typeof AuthenticatedCommandesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtelierRoute: AuthenticatedAtelierRoute,
  AuthenticatedCatalogueRoute: AuthenticatedCatalogueRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMesuresRoute: AuthenticatedMesuresRoute,
  AuthenticatedRendezVousRoute: AuthenticatedRendezVousRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedCommandesOrderIdRoute: AuthenticatedCommandesOrderIdRoute,
  AuthenticatedCommandesNouvelleRoute: AuthenticatedCommandesNouvelleRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedCommandesIndexRoute: AuthenticatedCommandesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
